In [121]:
import pandas as pd
import numpy as np
import json
import re

### Quartz Dataset

In [3]:
quartz_df = pd.read_csv('../Data/QuaRTz/quartz_dataset.csv')
print("quartz dataset columns: ", quartz_df.columns)
quartz_df.head()

quartz dataset columns:  Index(['id', 'question', 'choices', 'answerKey', 'para', 'para_id',
       'para_anno', 'question_anno'],
      dtype='object')

,id,question,choices,answerKey,para,para_id,para_anno,question_anno
0,QRQA-10385-4,"John's town used to have lots of water, back w...","{'text': array(['scarce', 'plentiful'], dtype=...",A,Many of the worlds people live with water scar...,QRSent-10385,"{'effect_prop': 'population growth', 'cause_di...","{'more_effect_dir': 'several thousand', 'less_..."
1,QRQA-10116-3,Electrons further away from a nucleus have ___...,"{'text': array(['higher', 'lower'], dtype=obje...",A,"Electrons at lower energy levels, which are cl...",QRSent-10116,"{'effect_prop': 'energy', 'cause_dir_str': 'cl...","{'more_effect_dir': 'higher', 'less_effect_dir..."
2,QRQA-10208-3,Milo threw both a basketball and a baseball th...,"{'text': array(['basketball', 'baseball'], dty...",A,An object with greater mass or greater velocit...,QRSent-10208,"{'effect_prop': 'kinetic energy', 'cause_dir_s...","{'more_effect_dir': 'more', 'less_effect_dir':..."
3,QRQA-10012-3,If greenhouse gases in the atmosphere were to ...,"{'text': array(['cooler', 'warmer'], dtype=obj...",B,If there are more greenhouse gases in the atmo...,QRSent-10012,"{'effect_prop': 'Earth temperatures', 'cause_d...","{'more_effect_dir': 'warmer', 'less_effect_dir..."
4,QRQA-10136-4,If you put a lot of energy into some food the ...,"{'text': array(['increase', 'decrease'], dtype...",A,The temperature of matter increases with the a...,QRSent-10136,"{'effect_prop': 'temperature', 'cause_dir_str'...","{'more_effect_dir': 'increase', 'less_effect_d..."

In [4]:
print("id: ", quartz_df['id'][10])
print("question: ", quartz_df['question'][10])
print("choices: ", quartz_df['choices'][10])
print("answerKey: ", quartz_df['answerKey'][10])
print("para: ", quartz_df['para'][10])
print("para_id: ", quartz_df['para_id'][10])
print("para_anno: ", quartz_df['para_anno'][10])
print("question_anno: ", quartz_df['question_anno'][10])

id:  QRQA-10286-1-flip
question:  When there are fewer carbon atoms in something there are
choices:  {'text': array(['many options', 'few options'], dtype=object), 'label': array(['A', 'B'], dtype=object)}
answerKey:  B
para:  A: The more carbon atoms there are, the greater the number of possible arrangements of carbon atoms.
para_id:  QRSent-10286
para_anno:  {'effect_prop': 'options there are', 'cause_dir_str': 'more', 'effect_dir_str': 'greater', 'cause_dir_sign': 'MORE', 'effect_dir_sign': 'MORE', 'cause_prop': 'carbon atoms'}
question_anno:  {'more_effect_dir': 'many', 'less_effect_dir': 'few', 'less_cause_prop': 'carbon atoms', 'more_effect_prop': 'options', 'less_effect_prop': 'options', 'less_cause_dir': 'options'}

In [5]:
def normalize_choices(choices):
    data_dict = eval(choices, {"array": np.array, "np": np})
    structured_choice = {
        "choices": [t for t in data_dict['text']],
        "answers": [l for l in data_dict['label']]
    }
    return json.dumps(structured_choice, ensure_ascii=False)

In [7]:
quartz_dataset = pd.DataFrame(data={"question": quartz_df['question'], "choices": quartz_df['choices'].apply(normalize_choices), "answer": quartz_df['answerKey'], "question_type": "MCQ", "dimension": "Logical Thinking"})
quartz_dataset.to_csv('../Data/Standrized_dataset/quartz_dataset.csv', index=False)

### Technical Computer science questions

In [21]:
def normalize_cs_choices(choices):
    question = choices['patterns'][0]
    answer = choices['responses'][0]
    return question, answer

In [29]:
dataset = pd.read_json('../Data/technical_CS/intents.json')
dataset.head()

                                             intents
0  {'tag': 'abstraction', 'patterns': ['Explain d...
1  {'tag': 'error', 'patterns': ['What is a synta...
2  {'tag': 'documentation', 'patterns': ['Explain...
3  {'tag': 'testing', 'patterns': ['What is softw...
4  {'tag': 'datastructure', 'patterns': ['How do ...

In [32]:
normalize_cs_choices(dataset['intents'][0])

('Explain data abstraction.',
 'Data abstraction is a technique used in computer programming to separate the implementation details of a data type from its interface, allowing the implementation to be changed without affecting the code that uses it. This is often achieved through the use of abstract data types (ADTs), which are defined by the operations they support rather than their specific implementation, or through the use of interfaces and classes in object-oriented programming languages. Data abstraction helps to reduce the complexity of software systems by allowing code to be written in a modular and flexible way and by hiding the underlying details of data types from the user.')

In [36]:
for index, row in dataset.iterrows():
    question, answer = normalize_cs_choices(row['intents'])
    dataset.at[index, 'question'] = question
    dataset.at[index, 'answer'] = answer

In [ ]:
dataset["answer"].head()

0    Data abstraction is a technique used in comput...
1    A syntax error is an error in the structure of...
2    Program documentation is written information t...
3    Software testing is the process of evaluating ...
4    A data structure is a way of organizing and st...
Name: answer, dtype: object

In [39]:
cs_dataset = pd.DataFrame(data={"question": dataset['question'], "answer": dataset['answer'], "question_type": "open-ended", "dimension": "Technical Thinking"})
cs_dataset.head()

,question,answer,question_type,dimension
0,Explain data abstraction.,Data abstraction is a technique used in comput...,open-ended,Technical Thinking
1,What is a syntax error,A syntax error is an error in the structure of...,open-ended,Technical Thinking
2,Explain program documentation. Why is it impor...,Program documentation is written information t...,open-ended,Technical Thinking
3,What is software testing?,Software testing is the process of evaluating ...,open-ended,Technical Thinking
4,How do you explain a data structure?,A data structure is a way of organizing and st...,open-ended,Technical Thinking

In [40]:
cs_dataset.to_csv('../Data/Standrized_dataset/cs_dataset.csv', index=True)

### Arc Dataset

In [56]:
arc_ds = pd.read_csv('../Data/arc_dataset.csv')
arc_ds.head()

,id,question,choices,answerKey
0,Mercury_SC_415702,George wants to warm his hands quickly by rubb...,"{'text': array(['dry palms', 'wet palms', 'pal...",A
1,MCAS_2009_5_6516,Which of the following statements best explain...,{'text': array(['The refrigerator door is smoo...,B
2,Mercury_7233695,A fold observed in layers of sedimentary rock ...,"{'text': array(['cooling of flowing magma.', '...",B
3,Mercury_7041615,Which of these do scientists offer as the most...,"{'text': array(['worldwide disease', 'global m...",D
4,Mercury_7041860,A boat is acted on by a river current flowing ...,"{'text': array(['west', 'east', 'north', 'sout...",B

In [ ]:
arc_dataset = pd.DataFrame(data={"question": arc_ds['question'], "choices": arc_ds['choices'].apply(normalize_choices), "answer": arc_ds['answerKey'], "question_type": "MCQ", "dimension": "Reasoning"}) 
arc_dataset.to_csv('../Data/Standrized_dataset/arc_dataset.csv', index=True)

### ReClor Dataset

In [72]:
train_reclor_ds = pd.read_json('../Data/ReClor/train.json')
test_reclor_ds = pd.read_json('../Data/ReClor/test.json')
reclor_ds = pd.concat([train_reclor_ds, test_reclor_ds], ignore_index=True)
reclor_ds.head()

,context,question,answers,label,id_string,question_type
0,"In rheumatoid arthritis, the body' s immune sy...","The statements above, if true, most strongly s...",[Unlike aspirin and other medications that red...,1.0,train_0,NaN
1,Patient: Pharmacists maintain that doctors sho...,The patient's argument proceeds by,[attempting to discredit a position by questio...,0.0,train_1,NaN
2,Paula will visit the dentist tomorrow morning ...,The pattern of reasoning displayed above most ...,"[If Marge goes to the bank today, Lauren will ...",1.0,train_2,NaN
3,Some theorists argue that literary critics sho...,The argument's conclusion follows logically if...,[Any critic who is able to help readers make t...,1.0,train_3,NaN
4,Shipping Clerk: The five specially ordered shi...,"If the shipping clerk's statements are true, w...",[At least one of the shipments sent to Truax C...,0.0,train_4,NaN

In [76]:
print("Context: ", reclor_ds['context'][152])
print("question: ", reclor_ds['question'][152])
print("answers: ", reclor_ds['answers'][152])
print("label: ", reclor_ds['label'][152])

Context:  Stylistic evidence and laboratory evidence strongly support the claim that the magnificent painting Garden of Eden is a work of the Flemish master van Eyck. Nevertheless, the painting must have been the work of someone else, as any one with a little historical and zoological knowledge can tell merely by looking at the painting. The animals in the painting are all vivid representations of actual animals, including armadillos. Yet armadillos are native only to the Americas, and van Eyck died decades before Europeans reached the Americas.
question:  In the argument given, the two highlighted portions play which of the following roles?
answers:  ['The first is a position that the argument seeks to reject; the second is evidence that the argument uses against that position.', 'The first is a judgment that serves as the basis for the main conclusion of the argument; the second states that main conclusion.', 'The first is an intermediate conclusion drawn in order to support a further conclusion stated in the argument; the second provides evidence in support of that intermediate conclusion.', 'The first presents the main conclusion of the argument; the second provides evidence in support of that conclusion.']
label:  3.0

In [ ]:
print()

In rheumatoid arthritis, the body' s immune system misfunctions by attacking healthy cells in the joints causing the release of a hormone that in turn causes pain and swelling. This hormone is normally activated only in reaction to injury or infection. A new arthritis medication will contain a protein that inhibits the functioning of the hormone that causes pain and swelling in the joints.
 The statements above, if true, most strongly support which one of the following conclusions?

In [89]:
reclor_dataset = pd.DataFrame(data={"question": (reclor_ds['context'] + " " + reclor_ds['question']), "choices": reclor_ds['answers'], "answer_idx": reclor_ds['label'], "question_type": "MCQ", "dimension": "Deduction & Induction"})
reclor_dataset.to_csv("../Data/Standrized_dataset/reclor_dataset.csv", index=True)

### OpenbookQA Dataset

In [100]:
openbookqa_ds = pd.read_csv('../Data/General culture/openbookqa_dataset.csv')
openbookqa_ds.head()

,question_stem,choices,answerKey,fact1,humanScore,clarity
0,The sun is responsible for,"{'text': array(['puppies learning new tricks',...",D,the sun is the source of energy for physical c...,1.0,2.0
1,When standing miles away from Mount Rushmore,{'text': array(['the mountains seem very close...,D,"as distance to an object increases , that obje...",1.0,1.4
2,When food is reduced in the stomach,{'text': array(['the mind needs time to digest...,C,digestion is when stomach acid breaks down food,1.0,1.6
3,Stars are,"{'text': array(['warm lights that float', 'mad...",C,a star is made of gases,1.0,1.6
4,You can make a telescope with a,"{'text': array(['straw', 'Glass', 'Candle', 'm...",D,Galileo Galilei made improvements to the teles...,0.8,1.0

In [110]:
openbookqa_ds['difficulty'] = openbookqa_ds['humanScore'].apply(lambda x: 'easy' if x >= 0.75 else 'medium' if x < 0.75 and x >= 0.5 else 'hard')

In [109]:
openbookqa_dataset = pd.DataFrame(data={"question": openbookqa_ds['question_stem'], "choices": openbookqa_ds['choices'], "answer": openbookqa_ds['answerKey'], "question_type": "MCQ", "dimension": "General Culture"})
openbookqa_dataset.to_csv('../Data/Standrized_dataset/openbookqa_dataset.csv', index=True)

### Creative Problem solving

In [112]:
cps = pd.read_excel('../Data/CPS/problem_solution_pair.xlsx')
cps.head()

,ID,Problem,Solvable?,Unconventional?,Solution,Label
0,541,You spilled red wine on the hotel carpet and w...,Yes,unconventional,Step1: Open the bottle of mineral water with t...,inefficient
1,542,You accidentally locked your only pair of glas...,Yes,conventional,Step1: Use the remaining battery in your smart...,infeasible
2,543,You have an important meeting but your suit is...,Yes,unconventional,Step1: Hang the suit on the coat hanger on the...,inefficient
3,544,The hotel bathroom door handle is broken and y...,Yes,unconventional,Step 1: Unbend the wire hanger and flatten it ...,inefficient
4,545,The hotel's WiFi signal is weak and you have a...,Yes,conventional,"Step1: Using the clothes hanger, create a hook...",infeasible

In [125]:
creative_problem_solving_dataset = pd.DataFrame(data={"problem": cps['Problem'], "solution": cps['Solution'].apply(lambda x: re.sub(r"<.*?>", '', x.replace('\n', ''))), "question_type": "open-ended", "dimension": "Creativity"})

In [130]:
creative_problem_solving_dataset.to_csv('../Data/Standrized_dataset/creative_problem_solving_dataset.csv', index=True)